name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - name: Create Archive
      uses: edgarrc/action-7z@v1.0.4
      with:
        args: 7z a opencheat.zip ./src/dist/windows/* user_prefs cheats

    - name: Upload Release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'opencheat.zip'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
